# Generated by Django 5.1.2 on 2024-11-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Toyota', 'Toyota'), ('Chevrolet', 'Chevrolet')], default='Ford', max_length=20),
        ),
    ]
