# Generated by Django 5.1.2 on 2024-11-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_vehiculo_descripcion_alter_vehiculo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
