# Generated by Django 5.1.2 on 2024-11-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_vehiculo_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': (('visualizar_catálogo', 'Permite ver los vehículos'),)},
        ),
    ]
